---
version: "2"
plugins:
  duplication:
    enabled: true
    exclude_patterns:
    - "tests/"
    - "genTravis.php"
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/BooleanArgumentFlag:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
  phpcodesniffer:
    enabled: true
  sonar-php:
    enabled: true
  phan:
    enabled: true
